---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - ./cilium/ks.yaml
  - ./coredns/ks.yaml
  - ./metrics-server/ks.yaml
  - ./reloader/ks.yaml
  - ./nfs-subdir-external-provisioner/ks.yaml
  - ./intel-resources-drivers/ks.yaml
components:
  - ../../components/namespace
