apiVersion: v1
kind: Secret
metadata:
    name: nordvpn-credentials
stringData:
    username: ENC[AES256_GCM,data:Pu5/0ZwaVKff9T51ayma6Gz8iHCCcb98,iv:cWkh3pdSJGKUGCAnuR4ilp68OswgqGmLIWQ+tP42uMs=,tag:ylWnn+iJMFUdx+W/oeqyjA==,type:str]
    password: ENC[AES256_GCM,data:pewxFtCOLcbCdcuYsnp2eyeQfFh7eeAa,iv:sMxdCHH30hG58ZdDPSjT9B7IdnNR7Xy4t1tzO5TH8n0=,tag:OdaS+M3gquQtAXWK7fpg9Q==,type:str]
sops:
    age:
        - recipient: age13x2kx6gsqu5zwk9ryqfess4k9ytl7c06wktnulalnq76kgpem4pqqhkj4y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSVjVyb1A0UU15L1FHMXFF
            L2NJaG5aZzVKeStyMmEzT0lSV3BXUjZQNGd3CkxHejh2Uk1yd1QvR2NJWE43UE04
            MnZhcXd4Slc2Q3Y4aEtDcWN5RWpHNDAKLS0tIDBkKzdiU3NncWR0UUZDZEV1c2t0
            c2FNcjl1TzB3N1JsM1dlVzdXYTV4d1EKSLPUgxsMgkruqEsrfO4GB+S16C8rWR/1
            axOuX6s8ZDKMvmJgPNIoFPMj/iF/H5PkIcTXPL/Wi2CSlBE1GS3krQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T19:13:48Z"
    mac: ENC[AES256_GCM,data:UFhCiDe8iUlymWNPfRZrupDZ4AXB4MtpZdgPpWdnVL22WS+8tiJuCqjZynNOf4Kha8Zkc+QEwvjpoNIr6rKwbGfGbFV8PAzfR2tyt4ld2R35y2Vtb/CkFLdtJbtwTffeuzik2JIyzJ6TMYGDndgpnzvwLcDhcx1i5VVArSOeT0Y=,iv:NM2QyslbFkLIOKTtXbbfuHFWQUFkv0UwFZcULdXsULU=,tag:aHDA5JgpqS9qo/jwI/qPFw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
