apiVersion: v1
kind: Secret
metadata:
    name: nordvpn-credentials
stringData:
    username: ENC[AES256_GCM,data:jxhsUkDfKsXBpWQRKotAnbzlQCuG2X6F,iv:cnsxfjcyu5i1OI4tj2cWNAEvriO5ZwGcIJePiQ39Qgg=,tag:9ufBnhBAZ7qFPX/lEyLtLg==,type:str]
    password: ENC[AES256_GCM,data:cJrCQrx9rz51gLRTxqOuTZUnZ3cR0WNw,iv:c52EeC/wE1NzfoMHrGesqovEYjzXW5EEeg2jmmI2bOQ=,tag:DEhcCVHZ1O05W6p5/d/pzQ==,type:str]
sops:
    age:
        - recipient: age13x2kx6gsqu5zwk9ryqfess4k9ytl7c06wktnulalnq76kgpem4pqqhkj4y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlUlFrdUh3NSthb3YvaVVT
            RnhaUzZXWXRHcnJkRFd4R0ZkL3FZMlJrR0FJCmg3ZlZaQkZCOXo2NndSRGNjSVJr
            b0luQUM1dFVqeVJKUXJLOE05TU1WTjgKLS0tIGM1NnJDcVliWmlWZ1ByZ3c2ZWVy
            ZUdxV1ptNTJtM0RUOEZ6OU56bVdtN1EKH2SNx1k8xLwia161J9eGIRgYIHSTYPIe
            9OvFQrWxo/hCOfBar9P3LIq4VEoLzUenuVMAPcjUaYuygAPusxvQ+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-13T23:08:03Z"
    mac: ENC[AES256_GCM,data:laDnXQHmZpZ1tOGgbLI8pKa51t3AEQkonZ+7KdpCotEgYL7z2rK3BNS5gkSoJB9arGQ0W/kAnVpmdk6OxWeQt8nao2NJFJRDcxVoNHUubr8PmBU6hBApNTLflMBXBs5U41jgvJPTax7vsdfJKjof33b2pU7J6ZmtejnknkKCbLs=,iv:QSl2axHmSPzqPIq8ktrmkkSZltvxhRt0aFROz43jiz8=,tag:27AVbVOmgtzQvOwWAX1sHQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
