apiVersion: v1
kind: Secret
metadata:
    name: qbit-credentials
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:VY+EiiY=,iv:bc6IS+nGOKBGyikLMeS2ESeB24x0JYIoDyP38dVBpog=,tag:lL+ymX7Owb5K5TIlxZI6OQ==,type:str]
    password: ENC[AES256_GCM,data:du4MLTGI8375dHw=,iv:doAxPUkWHen0sQfTtY8ss34fhCO1aqCWY2awmybHfTw=,tag:+K/2IYULVGoXNYD/mjai6A==,type:str]
sops:
    age:
        - recipient: age13x2kx6gsqu5zwk9ryqfess4k9ytl7c06wktnulalnq76kgpem4pqqhkj4y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmWktBUDJMS2dZOTFBeSt2
            OHNxMnZLd0xKUDdYN3ZIcHBGQ0l3WFdlWEY0CmZNc1NZMWJhVGFqV016WVpZYm5i
            TmszQjBDMmFRK2JvVXJTWHNpbCt6NDQKLS0tIFFmbXlsQnJTVzFOWkR3Z29TWXQ3
            UWRlM3ZQMllsMG1QTDZsOW1PNVZud2MKNtf6jKbTu4nHxybAkhNor4AbIPNdwr2D
            sqgezSWlSb/o7zGJfVUE5TZf+36eu/X0rAagFuKbG7Q2OZc4Scxyxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-13T23:08:03Z"
    mac: ENC[AES256_GCM,data:M5Qi1GtOWo4k0RhcCGRjTup4l59UsnQrTeLuifv6LYsXF63aSgUZ47/n3cUVQZahpx6EstGLuOepJhF6AhHeL8qFAMPHLh7I0VOy/C0YBS5HTFqCNmgOutpjWcn40RJwR0HZVG8sHycUdwkWIklugYiQFWJ9Db0hRHxb7TP8RAk=,iv:kMRkG5gj3tBJMJx3vOyvxpA0/gksPwF2zETStuxOvCg=,tag:30WbDbr54gIxsa2goieiQg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
