---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cleanuparr
spec:
  interval: 1h
  path: ./kubernetes/apps/downloads/cleanuparr/app
  postBuild:
    substitute:
      APP: cleanuparr
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: downloads
