apiVersion: v1
kind: Secret
metadata:
    name: external-dns-unifi-secret
type: Opaque
stringData:
    UNIFI_API_KEY: ENC[AES256_GCM,data:wUzXMKH3Ky+GEWe/VFvDqjRp+z1t62VoitmfdP/xtG4=,iv:Qk+9GKBcavxcnZ1brkern7q3agBvumk4HL3KP8HOp8E=,tag:wfwVeLstj+pXZn6DcYZz8A==,type:str]
sops:
    age:
        - recipient: age13x2kx6gsqu5zwk9ryqfess4k9ytl7c06wktnulalnq76kgpem4pqqhkj4y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuclpxMEFxTGtTL09vU2sz
            L0wvbkludGJNd3NPTFkyamlOQXEraWdvQ1ZBCmJiY3pxeDZoSkh2TTEycVhyTEFQ
            UUVRUUprUUJIL01xaXB0eDVkbG1nU1UKLS0tIFBQeEFISUIvc0ZVZFdGN0t4aFVo
            WnZqUFpDbFc4Q2NsTVRUeXIxZG1wUGMK4c8yC1sVG3AUpQCv+zxyS1pPkBKZNJab
            9PYoZUBCxTRi49jcwH7UeSWKiNDeM9vnqLOZiIZQqUUbUkgyuLWm2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-02T22:46:46Z"
    mac: ENC[AES256_GCM,data:JxjgH/dJ0wc/sg0riw09hU+9YKK1mqiaGtwqS9i4rnl/IngZ4IVx649bkx27fxZnqnN3Z6po6JjGtv6uSRzsQEu7kIH6p8Kkf960hYyJ1k4W2qvAfk4hzQQmIHhR7JjLQUzpl+1+buh1lANeerCNcu/AeRrw+vii+VL+tt+ciJg=,iv:M5797KOugfKd0brbjxuqRYfXYsmzrD2Umv+PWZFhNt4=,tag:QIuCMTtYAKuA1apwDSDoBA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
