apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: intel-gpu-rule
spec:
  rules:
    - name: "intel-gpu-detection"
      labels:
        intel.feature.node.kubernetes.io/gpu: "true"
      matchFeatures:
        - feature: kernel.enabledmodule
          matchExpressions:
            i915:
              op: In
              value: ["true"]
