apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-secret
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:EKXXj1mW8xQIdO1/pk2Pag+kwzu1QjF7efGlYuPNAt5s+NpGiPM8BRPmho7T6/pm85Clg/mHY82iUyg8cmt5PA==,iv:VugbCibmXrS9rFOnL9v2cLBT0hZ9KLLAa1yl9ag2w3w=,tag:Aew0wbGpJjnVvWP6A0P7DA==,type:str]
sops:
    age:
        - recipient: age13x2kx6gsqu5zwk9ryqfess4k9ytl7c06wktnulalnq76kgpem4pqqhkj4y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvNkREYm1ZQmdpc3h0aFhS
            NkxrdGVQVDJuT0d0U2t4YUdDWDkzSFM2T0QwClJOSG1Ya0JHTm4yRklMc0IrdSs2
            akxoRWhmVk1wck5kNXR1bXc4Z0N1TG8KLS0tIHdsM0dLYktFYUx5WGJ6eWdZaGRl
            RUp3RXdCTytvUm51eXVsSjlBeGE2VzAKQWjEynaxX0KEmKHoqINUS6Op6pBp8t+P
            kMg6PIo5tDYOIGW2Yj5+Nv/qjgUf2buwZ57xKEG5BmDqmZjHUdfCFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-13T23:08:03Z"
    mac: ENC[AES256_GCM,data:n43vilv15G7NUp+g2GQxeppVvj6geD+GdcxNlcaFf49sQ2J7tuFW+TcNvnk+LczJVp9dcQoyvIFDSjzlGDEvtxlMIJd/QGROoZkxtWyGqFMVP33sUd+l/8R/fUC8ygLXC0Mi29+e7ux6GjVlZK9BpOWoEk5lzKPKCzTgIRK4WPE=,iv:xtC1NbOCB83rQ+aCLlKyNniT5rAQjfU+jpEDr77+u6I=,tag:1C4g/8TH4GHvxoZhtDGfQA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
