apiVersion: v1
kind: Secret
metadata:
    name: sops-age
type: Opaque
stringData:
    age.agekey: ENC[AES256_GCM,data:Z5FQvMWbM5MKFDARoEPlM2nU59pTgn+ZvCvkvED4GySa8yJL/G6IZMxwVRd4CewfB9z6bbDza3BizHb06Vq7YZZGXfrBDb9/2+kG,iv:pJCNzyLhbvXY764gIWNZ5YWFRtCAIUfwx5eS2NboaeE=,tag:cAiF66EFI55JXYJ5UMSqLg==,type:str]
sops:
    age:
        - recipient: age13x2kx6gsqu5zwk9ryqfess4k9ytl7c06wktnulalnq76kgpem4pqqhkj4y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLd0VNNEhoMWozQ0Y4NmZB
            YkJWMjNSQnB1RDBUNHhqZVRoWEdYMzBnT1JJCkVTMXpyVHdQL0hiSlJxNlplMW84
            UWEvendjMUVDSExZa1ZpZWxWaDBUT0UKLS0tIGNVQitDeEowTnVLWElmTURLWVpX
            OEVNREN6Uk1vVjhpZXJyZ0lDSmVEQjQKW+Wf8uKBUbwqHKU11/5KFMP20/UvweNK
            ND4FSvKxis1iywlWst4W6LQlR4acfZMk4jJH1DBkKcHqeJkgmmBLkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-13T23:08:03Z"
    mac: ENC[AES256_GCM,data:e2D8OfBg8IDo132VjYClHPsnBzxXNWjh2YbN+1xg5WdlhvCxd+ANFnsU1Ie27U7LKbyioujruqZCk2y5BzKP3zeE6AH8dOzQkxbgjP9ukzL5jovYKW65cV44ZmQRbFNVVzl32Tn5Um8btLqrLOV4mphhVnI+S4YV9GeJvnevkkc=,iv:biwITDlXpdBipSbRn7kzrkeIS1XaDhPrblE09et3hQw=,tag:XO2YRS6vPGXW3g8mVWfDwg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
