apiVersion: v1
kind: Secret
metadata:
    name: external-dns-pihole-secret
type: Opaque
stringData:
    PIHOLE_SERVER: ENC[AES256_GCM,data:UfwPCyTOyfMS1GYKTlby3CAjKbkpDW+3,iv:AP+qLemN4exqmgWyynXngcGhfPSaT0gpkjBnZXsqU0A=,tag:VwYn/KJH/tisijCq2S9Mlg==,type:str]
sops:
    age:
        - recipient: age13x2kx6gsqu5zwk9ryqfess4k9ytl7c06wktnulalnq76kgpem4pqqhkj4y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxY0x3RXNkOEhoYTlvREZ1
            Zko5cDBpREFDbnh0MnJzMXh1bi9MVTZOSTE0Cmd0ckExUkNETUZkeVhyRG1iMmNw
            VDNaQUVQMEdCOFVmVnBLd1Bhalg2b3cKLS0tIGhoMGhFbUVGNEdPdm5zWnpBWnFF
            UkNETUV0MjZEcEUxOFV0dEdmNmtOdGsKoNEqabuD1pdDkt+XnZ60MVr/WPKk408L
            sOwFm0S23ASbprcGJuryt4OI/ZUnm4F8lH2krHxII894leDlJfwX4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-13T23:08:03Z"
    mac: ENC[AES256_GCM,data:y5K8I4QIV6A+OCdL5PqpED6x8HfyFQqmW0YsxMe7scUBOa7csXv1jzd/+/lhQOLbDfsHVo7aUwBJO3nh/gQYCpnE4xAOwb0VI2RyH8Nwvu3/tOmMFqMypmZk93F+vvmp+o1mquuly5+UvqtyC06cpRz1rwMZbL6zQscOqGCBtNw=,iv:OXEpCymnS1Qhs99ZsXcjDafZBgeSzwSGf1fdbhbUsUg=,tag:/bFW2wo72TYUjD83o6f17Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
