apiVersion: v1
kind: Secret
metadata:
    name: external-dns-pihole-secret
type: Opaque
stringData:
    PIHOLE_SERVER: ENC[AES256_GCM,data:Kfc18a0J7PFxbwRmSYQFUBem6g3AhcvoaQ==,iv:idy7UbQ7d4Ni+fBwKlQVsXcXd8S64wTamXDF41LZNJc=,tag:7v2HLiu0V0EIS+M46DySDQ==,type:str]
sops:
    age:
        - recipient: age13x2kx6gsqu5zwk9ryqfess4k9ytl7c06wktnulalnq76kgpem4pqqhkj4y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3QzVlQS9oSGhJMDhHSFM4
            Ni9lN3NqQmtyQjFmNGdORHQ2K0sxbmEyMDFVCm53UUFqT1p6eTRJakpsNTFsU2Nl
            UlVESWdwVm95SlE1VERqWkViRlh6M3MKLS0tIHJKTzNWS21UNjIycHRIMnpBVGNY
            RHR0NmFkY25IclByazh2aUVmY2VtODgKeamRqICrRJpTg8BP/lW/SPsw3/CcoC42
            yGigNnjYIn2NYy1udBiODMPfCm74TtGBIht46oweGW8L+GbiQVABIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-02T01:59:35Z"
    mac: ENC[AES256_GCM,data:LMQk9ct0Mt3aLb3TYvLU3a5u1+aATCS3igU8iV5DNoLKy/W0i+YdIIIQTydNJe3fBCebHot5qQ6sqFXcZSyaTwmyyNlgvFRSjmR6y2h3XP2rW7Y0BS5SNMuHjoa4cB1AhoMtqpwg1Xk+8OVqcPPIxb3LUbaZNYJO8EinU0PID2o=,iv:Ncr1iDxuCjPs30s4DD+7kDTqImaK2xGTTqjEptfytFM=,tag:Z12zaRVKYJvF1rCHrbFdKw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
