apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloudflare-secret
stringData:
    CF_ZONE_ID: ENC[AES256_GCM,data:Ft0wPr2CV8ZmVaM8txEickfA3IVKZBIHeawJCj1yTCY=,iv:jR+doVjW3qtKYcMOT69cJsTymsaNMwC5FoYpapjWWPo=,tag:FSTlp2d1TPleXJuUsDrqjw==,type:str]
    CF_API_TOKEN: ENC[AES256_GCM,data:aloYH6Tq1HoVghs8PzvNs105fTacQdu+hmJbEIEk3XZAP88iGDj/Bg==,iv:+sv7EbpuURyPW66i2JOk5kXW5CGdHkH4c5mTRRmcFuU=,tag:+LNfvz1bAFubJvs+f8MPPw==,type:str]
type: Opaque
sops:
    age:
        - recipient: age13x2kx6gsqu5zwk9ryqfess4k9ytl7c06wktnulalnq76kgpem4pqqhkj4y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaYmFpWDI1K04yd2pqZ2F0
            VTZUY3A5SENnWnU0WUNnbzlBaEJxUkhYaDJBCks4NFF2bm5XcTNzc0h5em5tQ0M1
            QW1tRSt6NG1KUTV0UnNEN2lBRnRtcFUKLS0tIE9xVy8rb1VnU1U4S2RvUlJCakFL
            aWM2ZGY3RUVUNzFTTmxvSHozNkp5U1UKZSBLzJLA5GQPCFjrBpUacZJRSoYqBB1i
            CDQfYL1ebc2+n5XeWQjK84v/UP8SSLO2RsxLyRIRVlw8hmd4B/eQ0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-13T23:08:03Z"
    mac: ENC[AES256_GCM,data:QSs8o49IiBpe/RnlxAcyd8oYAEDegjx+muRorZT5RvMYdEqpDOU9iCfOSWqZB1qXzyZlFzIe/XvjqVlIAu5X1bIvpOUnIijOH5uWZF8LfXUTBVKG8Hnz+bgAEkTX7+7tEcs+iRh8AAyWL06i4yOCpjwDebDc1F0nZkRhbkYjWGQ=,iv:ckUDLQErutPRMlc0QRdjIXYRXNWkqxXD+xwaLFTpb7w=,tag:uZWlnbTYqxVhYMQMIBvUtw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
