---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./recyclarr-secrets.sops.yaml
configMapGenerator:
  - name: recyclarr-configmap
    files:
      - ./resources/recyclarr.yaml
generatorOptions:
  disableNameSuffixHash: true
