apiVersion: v1
kind: Secret
metadata:
    name: recyclarr-secret
type: Opaque
stringData:
    RADARR_API_KEY: ENC[AES256_GCM,data:qOnreHJ146zlNIjckxM1cPTn8JoyE+rkkOh9JSwd21s=,iv:W+2XDcMRDYEhyYv5tQ8dnbespv+9R/L0l3kgBjmGXws=,tag:GdtolqzBO7k3EKpX0DuTbA==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:QJWIpqFaJ4+TGQ5+IhuH4eHcP+jA3Uxo5PrJPNwhQaA=,iv:AVdfBwBMsulBPzUJvOQEZ0gOaLpMg97ztyubICL328M=,tag:KAgQ24d4Nxokl0ay2i4ZYA==,type:str]
sops:
    age:
        - recipient: age13x2kx6gsqu5zwk9ryqfess4k9ytl7c06wktnulalnq76kgpem4pqqhkj4y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArTkxXNHFVK1FKa2I3SGdY
            R0xYYjdFanZqZ1ZjbEFZWlZaVFprU2ZoNTNRCkI3eXFldFV5THUwc1lvMDFkQmV3
            U3FSKzhCSU4zVkt3dis2NGIxSHc1L2MKLS0tIE01M0ZldmFBU252MnN5RER4aklI
            dFlQQ2JZaTZQZFJmdkVxWHIyM1R4NVkKoUkailebXdm+KnEzaCNgKe1h6/DfSG26
            EAqnG+mQeE9sxOvMWc965LSPP9s7Y9skY3cJX/yKHRnircFWN01Asg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-13T23:08:03Z"
    mac: ENC[AES256_GCM,data:s12f+9DIhNFLqu81N7uVyjcBPnpIseFzewuOT5Kwu6wfmEBPvPKR6gOhrRJLNB+kotT+u4Ul9ntKqR+ERk+U22lAkTm14PcXUwPh5vAsARCEFVyvmaY01zWaLHHgVCWn0c+xMGJ3HtphuQ9OgJ24+rS++x8lTTYaEuWz3dUW4Ds=,iv:633zqa9p3Pkz4ZO+2zam7zg9FqKYhV7cesPTHOE+1yM=,tag:kaox2xId1xcv/oZRA3JHnw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
