apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-issuer-secret
type: Opaque
stringData:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:hraFqkT+mWVsg2QnVfH5kYYxhlb/nWpgF352vUL6NQAl+aTcBdYSsA==,iv:g7bht8bNvhsUYxHtiNuoSi1rXZEX1Ttaaxs2aa5wDfg=,tag:OBZ8n0XRb4PagkKhzbVOLw==,type:str]
sops:
    age:
        - recipient: age13x2kx6gsqu5zwk9ryqfess4k9ytl7c06wktnulalnq76kgpem4pqqhkj4y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3V3RIMEZEOWNXK1FlT1Nt
            YjUwUklUSllFUU1LeWlCNUdMUVBkVUZ6bWs0CkZZL1UxelhJdGVXVHErNTFNQTFj
            d1AxTGZzOGtvdFROaU5Yc3VPM3Q1ZnMKLS0tIElFZElaSXlvK1R2a0ovcDFSZmlL
            VW9YbjhweFZDbFFpSTl2ZVcyUk5pRGMK1I19vDGO8b5QHvcZRuod+Om0wK4QGENG
            x63bMz5VTZSCghx3nwa+YgnkJr9xyanuvvl4wBZwQ5Rkbd/0EAxmgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-13T23:08:03Z"
    mac: ENC[AES256_GCM,data:b+BN7xUWpQtQRF9Q9N7FPuH4fgB6LdDnVB9J4CYHdgkAYP6N/aJHsj/01ZCyDk+vjur+3y1wNFEEaS6J0crWBs1auIWJfcN3FQGgnDPcRvs8LnMDdFekFAl+viDvvmhT+q7WicAOxsfczOcZFxhOouBznngeKovRQGKzKER93U4=,iv:1kqC5WCumCi7o3rZUX9tsrWCsssnLFqjPD7gqvFgbxg=,tag:qTRofXiqySJytOaZnvRYyg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
