---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - ./gatus/ks.yaml
  - ./otel/ks.yaml
  # - ./grafana/ks.yaml
components:
  - ../../components/namespace
