apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:pkS3oMzvcaLVQGQYq5QT2NC2E3jyWqAAwjxLSBgGncr/jL5w5Ov9tw8DVcxkWpRcMd5CRkqholAUC/gVeX95ql4r6p6dfVX3jIDLuLPkJWNhI5ucbapmWymjvsUUX6Oh/QGHDgLoDu2ubk2G4Ke4Gw7wpPgsMnPvLVdt4OrSw7vbQ/U1j7HvshQOM6q/LsRTCw6S75/4VjwW9T75S0bujFD0h+ndn0szfXoqhuVe/aJp51qjezuaWA==,iv:bx8MnqpdT0HcCZ1p/titsQI7V30uzc5y/yUnh6rUG9A=,tag:K/GIH8Nz3qXE0BIAUXAM5A==,type:str]
sops:
    age:
        - recipient: age13x2kx6gsqu5zwk9ryqfess4k9ytl7c06wktnulalnq76kgpem4pqqhkj4y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwNlNGMG90NVhWcTlGZ2w2
            MzQvOThjZDNjUTBwUWxTZGJHR3JSem5Vb3dNCjIxWTUwZStNZGJmZzlJWTI2SXc0
            YVJDTnBOcWxQejhBUTdlckQ2ZWttNTAKLS0tIEI0NkhOMjhEZVUxRHI2N1NwM0dI
            RmdOZFBxTFhYeHFkZ0JzQVcydStpZzAKtCH87+L0q7XgUZX+NpssbdDkf9wbSXR4
            VvVUtJ0FqOsi+Hc+t1Rf2Nt/CxmjY9Rn6k32kDifeX/IVQfLaFrFCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-13T23:08:03Z"
    mac: ENC[AES256_GCM,data:rOFOk5RE/wI0I1XCvEv3m3C96AV8oJUipTXkI7e+or5JZXPIJAmCDHZVBmTGPA4EYhEJJkQXsTvSuLNcAJQTPHZ8q2aMw+SeoBaM4lHc99QV0X/qEji3/UPdzC5tTkzhY9XUqo2fPozOmePj4Izy2lQ+y2Mj84QKIHe990MHjAw=,iv:o27VzAAy//IJJ6v48qkGH1l6I0FOt/VIXoaV9PUtA60=,tag:Hlsv2hGqpwqAn35YzrdGRw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
