---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: opentelemetry-charts
  namespace: flux-system
spec:
  interval: 2h
  url: https://open-telemetry.github.io/opentelemetry-helm-charts
  timeout: 3m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: otel-operator
spec:
  interval: 60m
  timeout: 15m
  install:
    timeout: 20m
  chart:
    spec:
      chart: opentelemetry-operator
      version: 0.93.1
      sourceRef:
        kind: HelmRepository
        name: opentelemetry-charts
        namespace: flux-system
